version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: voc-app_development
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/workdir