default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root

development:
  <<: *default
  database: voc-app_development
  password: password
  host: db
  
test:
  <<: *default
  database: voc-app_test
  password: password
  host: db

production:
  <<: *default
  database: voc_production
  password: 
  socket: /var/lib/mysql/mysql.sock