default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db
  
development:
  <<: *default
  database: voc-app_development
  
test:
  <<: *default
  database: voc-app_test

production:
  <<: *default
  database: voc_production
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock