default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db

development:
  <<: *default
  database: voc-app_development
  host:
  password:
  
test:
  <<: *default
  database: voc-app_test
  password:
  host:
  password:

production:
  <<: *default
  database: voc_production
  password: 
  socket: /var/lib/mysql/mysql.sock